///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FetchDemoTst
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FetchDemoTstRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e34a5d9d-21a2-41ba-bfec-7d75631840e1")]
    public partial class FetchDemoTstRepository : RepoGenBaseFolder
    {
        static FetchDemoTstRepository instance = new FetchDemoTstRepository();
        FetchDemoTstRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the FetchDemoTstRepository element repository.
        /// </summary>
        [RepositoryFolder("e34a5d9d-21a2-41ba-bfec-7d75631840e1")]
        public static FetchDemoTstRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FetchDemoTstRepository() 
            : base("FetchDemoTstRepository", "/", null, 0, false, "e34a5d9d-21a2-41ba-bfec-7d75631840e1", ".\\RepositoryImages\\FetchDemoTstRepositorye34a5d9d.rximgres")
        {
            _rxmainframe = new FetchDemoTstRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e34a5d9d-21a2-41ba-bfec-7d75631840e1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("ff6d3e1e-05a1-44ee-acf2-7e1207073251")]
        public virtual FetchDemoTstRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FetchDemoTstRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("ff6d3e1e-05a1-44ee-acf2-7e1207073251")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _datagridview1Info;
            RepoItemInfo _treeviewInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "ff6d3e1e-05a1-44ee-acf2-7e1207073251", "")
            {
                _datagridview1Info = new RepoItemInfo(this, "DataGridView1", "?/?/tabpage[@controlname='RxTabUIElements']/table[@controlname='dataGridView1']", "", 30000, null, "d5d97931-ab0a-4a85-bc10-34da7e0b9847");
                _treeviewInfo = new RepoItemInfo(this, "TreeView", "?/?/tabpage[@controlname='RxTabUIElements']/?/?/tree[@accessiblename='Tree view']", "", 30000, null, "7903a089-b953-4584-8785-fd9439fccedd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ff6d3e1e-05a1-44ee-acf2-7e1207073251")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ff6d3e1e-05a1-44ee-acf2-7e1207073251")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DataGridView1 item.
            /// </summary>
            [RepositoryItem("d5d97931-ab0a-4a85-bc10-34da7e0b9847")]
            public virtual Ranorex.Table DataGridView1
            {
                get
                {
                    return _datagridview1Info.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The DataGridView1 item info.
            /// </summary>
            [RepositoryItemInfo("d5d97931-ab0a-4a85-bc10-34da7e0b9847")]
            public virtual RepoItemInfo DataGridView1Info
            {
                get
                {
                    return _datagridview1Info;
                }
            }

            /// <summary>
            /// The TreeView item.
            /// </summary>
            [RepositoryItem("7903a089-b953-4584-8785-fd9439fccedd")]
            public virtual Ranorex.Tree TreeView
            {
                get
                {
                    return _treeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The TreeView item info.
            /// </summary>
            [RepositoryItemInfo("7903a089-b953-4584-8785-fd9439fccedd")]
            public virtual RepoItemInfo TreeViewInfo
            {
                get
                {
                    return _treeviewInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
